env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi: off
overrides:
  - files:
      - "**/*.ts"
      - "**/*.tsx"
    plugins:
      - '@typescript-eslint'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    extends:
      - plugin:@typescript-eslint/recommended
      - airbnb-typescript/base
    rules:
      semi: off
      no-console: off
      "@typescript-eslint/semi": [ "error", "never" ]
      "@typescript-eslint/no-var-requires": off
      "import/extensions": [ "error", "never", { "json": "always" } ]
